server:
  port: 7001
eureka:
  instance:
    hostname: localhost1
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  client:
    allow-redirects: false
    fetch-registry: false